---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: _config.yml
  label: config
  match: "**/*"
- type: document
  path: robots.txt
  label: robots.txt
- type: document
  path: 404.html
  label: '404'
- type: document
  path: index.html
  label: index
- type: directory
  path: _posts
  label: Posts
  create: documents
  match: "*.md"
  templates:
  - default
  - post
- type: directory
  path: _pages
  label: Pages
  create: documents
  match: "*.md"
upload_dir: assets/images
public_path: "/assets/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
