---
label: default
hide_body: false
fields:
- name: title
  type: text
  config:
    required: true
  label: title
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: description
- name: categories
  type: tag_list
  default: []
  label: categories
- name: tags
  type: tag_list
  default: []
  label: tags
- name: image
  type: file
  config:
    maxSize: 64
  label: image
- name: featured
  type: boolean
  label: featured
  hidden: false
- name: hidden
  type: boolean
  label: hidden
