---
label: Post
hide_body: false
fields:
- name: title
  type: text
  config:
    required: true
  label: title
- name: description
  type: textarea
  default: ''
  config:
    required: true
    wysiwyg: false
    schema:
      format: markdown
  label: description
- name: permalink
  type: text
  config:
    required: false
  label: permalink
- name: date
  type: datetime
  label: date
  description: ''
  config:
    required: false
    date_format: 
    time_format: 
    display_utc: false
- name: image
  type: file
  config:
    maxSize: 64
  label: image
- name: hidden
  type: boolean
  label: hidden
- name: categories
  type: tag_list
  default: []
  label: categories
- name: toc
  type: boolean
  label: Table of contents
- name: author
  type: select
  default: []
  config:
    required: true
    options:
    - mat
    - pat
    source:
      type: simple
      section: 
      file: 
      path: 
  label: author
- name: layout
  type: text
  config:
    required: true
  label: layout
  hidden: true
  default: post
pages:
- _posts/2016-12-15-mortgage-before-marriage.md
- _posts/2017-02-20-renting-with-friends-5-reasons-you-and-your-friends-should-consider-buying-together.md
- _posts/2017-03-29-you-can-t-afford-to-buy-a-home-in-seattle-or-can-you.md
- _posts/2017-10-25-buying-a-home-with-your-boyfriend-or-girlfriend-part-i.md
- _posts/2017-11-26-buy-vs.rent-neither.md
- _posts/2017-12-11-10-reasons-you-may-want-to-buy-a-home-now.md
- _posts/2017-12-12-cobuy-greater-seattle-housing-market-survey.md
- _posts/2018-02-20-how-to-buy-a-home-with-your-boyfriend-or-girlfriend-part-2.md
- _posts/2018-03-25-should-you-form-an-llc-to-co-buy-a-home.md
- _posts/2018-04-25-co-buying-a-home-pick-the-right-deal-team.md
- _posts/2018-06-10-cobuy-greater-seattle-housing-market-update-may-2018.md
- _posts/2018-06-13-co-owning-a-home-how-to-split-ownership-between-co-buyers.md
- _posts/2018-08-28-how-to-cobuy-a-home-the-right-way.md
- _posts/2018-09-30-top-10-myths-about-cobuying-a-home.md
- _posts/2018-10-17-how-three-millennials-bought-their-dream-home-together.md
- _posts/2018-11-12-cobuy-greater-seattle-housing-market-update-nov-2018.md
- _posts/2018-12-03-case-study-how-co-ownership-helped-a-mother-son-meet-their-unique-goals.md
- _posts/2018-12-03-cobuy-greater-seattle-housing-market-update-dec-2018.md
- _posts/2019-01-02-cobuy-greater-seattle-housing-market-update-jan-2019.md
- _posts/2019-01-05-housing-market-survey-greater-seattle-jan-19.md
- _posts/2019-01-13-bay-area-housing-market-update-jan-19.md
- _posts/2019-02-07-greater-seattle-housing-market-update-feb-19.md
- _posts/2019-02-08-housing-market-survey-greater-seattle-feb-19.md
- _posts/2019-02-13-bay-area-housing-market-update-feb-19.md
- _posts/2019-03-10-bay-area-housing-market-update-mar-19.md
- _posts/2019-03-19-greater-seattle-housing-market-survey-march-19.md
- _posts/2019-04-13-bay-area-housing-market-update-april-2019.md
- _posts/2019-04-14-greater-seattle-housing-market-survey-april-19.md
- _posts/2019-06-17-bay-area-housing-market-update-june-2019.md
- _posts/2019-06-23-greater-seattle-housing-market-update-summer-2019.md
- _posts/2019-08-05-bay-area-housing-market-flash-august-2019.md
- _posts/2019-09-12-co-buying-a-home-with-a-little-help-from-the-bank-of-mom-dad.md
- _posts/2019-09-13-mortgage-before-marriage-read-this-first.md
- _posts/2019-10-07-cobuy-certified-mortgage-pro-trevor-reese.md
- _posts/2020-08-03-bay-area-housing-market-update-may-2019.md
- _posts/2020-08-06-cobuy-bay-area-housing-market-update-dec-2018.md
- _posts/what-a-rate-hike-means-for-buyers.md
