---
label: Post
hide_body: false
fields:
- name: title
  type: text
  config:
    required: true
  label: title
- name: description
  type: textarea
  default: ''
  config:
    required: true
    wysiwyg: false
    schema:
      format: markdown
  label: description
- name: author
  type: select
  default: []
  config:
    required: true
    options:
    - mat
    - pat
    source:
      type: simple
      section: 
      file: 
      path: 
  label: author
- name: categories
  type: tag_list
  default: []
  label: categories
- name: image
  type: file
  config:
    maxSize: 64
  label: image
- name: featured
  type: boolean
  label: featured
  hidden: false
- name: hidden
  type: boolean
  label: hidden
- name: date
  type: datetime
  label: date
  description: ''
  config:
    required: false
    date_format: 
    time_format: 
    display_utc: false
- name: permalink
  type: text
  config:
    required: false
  label: permalink
- name: layout
  type: text
  config:
    required: true
  label: layout
  hidden: true
  default: post
pages:
- _posts/cobuy-certified-mortgage-pro-trevor-reese.md
