---
label: Post
hide_body: false
fields:
- name: title
  type: text
  config:
    required: true
  label: title
- name: description
  type: textarea
  default: ''
  config:
    required: true
    wysiwyg: false
    schema:
      format: markdown
  label: description
- name: hidden
  type: boolean
  label: hidden
- name: categories
  type: tag_list
  default: []
  label: categories
- name: image
  type: file
  config:
    maxSize: 64
  label: image
- name: toc
  type: boolean
  label: Table of contents
- name: author
  type: select
  default: []
  config:
    required: true
    options:
    - mat
    - pat
    source:
      type: simple
      section: 
      file: 
      path: 
  label: author
- name: date
  type: datetime
  label: date
  description: ''
  config:
    required: false
    date_format: 
    time_format: 
    display_utc: false
- name: permalink
  type: text
  config:
    required: false
  label: permalink
- name: layout
  type: text
  config:
    required: true
  label: layout
  hidden: true
  default: post
pages:
- _posts/2019-02-13-bay-area-housing-market-update-feb-19.md
- _posts/2019-03-10-bay-area-housing-market-update-mar-19.md
- _posts/2019-03-19-greater-seattle-housing-market-survey-march-19.md
- _posts/2019-04-13-bay-area-housing-market-update-april-2019.md
- _posts/2019-04-14-greater-seattle-housing-market-survey-april-19.md
- _posts/2019-06-17-bay-area-housing-market-update-june-2019.md
- _posts/2019-06-23-greater-seattle-housing-market-update-summer-2019.md
- _posts/2019-08-05-bay-area-housing-market-flash-august-2019.md
- _posts/2019-09-12-co-buying-a-home-with-a-little-help-from-the-bank-of-mom-dad.md
- _posts/2019-09-13-mortgage-before-marriage-read-this-first.md
- _posts/2019-10-07-cobuy-certified-mortgage-pro-trevor-reese.md
- _posts/2020-08-03-bay-area-housing-market-update-may-2019.md
- _posts/housing-market-survey-greater-seattle-feb-19.md
