---
label: default
hide_body: false
fields:
- name: title
  type: text
  config:
    required: true
  label: title
- name: description
  type: textarea
  default: ''
  config:
    required: true
    wysiwyg: false
    schema:
      format: markdown
  label: description
- name: author
  type: select
  default: []
  config:
    required: true
    options:
    - mat
    - pat
    source:
      type: simple
      section: 
      file: 
      path: 
  label: author
- name: categories
  type: tag_list
  default: []
  label: categories
- name: tags
  type: tag_list
  default: []
  label: tags
- name: image
  type: file
  config:
    maxSize: 64
  label: image
- name: featured
  type: boolean
  label: featured
  hidden: false
- name: hidden
  type: boolean
  label: hidden
- name: permalink
  type: text
  config:
    required: false
  label: permalink
pages:
- _posts/2020-07-31-5-housing-market-trends-to-watch-in-2020.md
